#include <stdio.h>
#include <string.h>

// Função para exibir o menu de atributos
void mostrarMenu(int opcao_excluida) {
    printf("\nEscolha um atributo para comparar:\n");
        if (opcao_excluida != 1) printf("1 - População\n");
            if (opcao_excluida != 2) printf("2 - Área\n");
                if (opcao_excluida != 3) printf("3 - PIB\n");
                    if (opcao_excluida != 4) printf("4 - Pontos turísticos\n");
                        if (opcao_excluida != 5) printf("5 - Densidade demográfica\n");
                        }

                        int main() {
                            // Dados da Carta 1
                                char nome1[50];
                                    unsigned long int pop1;
                                        float area1, pib1, dens1;
                                            int pt1;

                                                // Dados da Carta 2
                                                    char nome2[50];
                                                        unsigned long int pop2;
                                                            float area2, pib2, dens2;
                                                                int pt2;

                                                                    // Entradas
                                                                        printf("Carta 1 - Nome do país: ");
                                                                            scanf(" %[^\n]", nome1);
                                                                                printf("População: ");
                                                                                    scanf("%lu", &pop1);
                                                                                        printf("Área (km²): ");
                                                                                            scanf("%f", &area1);
                                                                                                printf("PIB (bilhões): ");
                                                                                                    scanf("%f", &pib1);
                                                                                                        printf("Pontos turísticos: ");
                                                                                                            scanf("%d", &pt1);
                                                                                                                dens1 = pop1 / area1;

                                                                                                                    printf("\nCarta 2 - Nome do país: ");
                                                                                                                        scanf(" %[^\n]", nome2);
                                                                                                                            printf("População: ");
                                                                                                                                scanf("%lu", &pop2);
                                                                                                                                    printf("Área (km²): ");
                                                                                                                                        scanf("%f", &area2);
                                                                                                                                            printf("PIB (bilhões): ");
                                                                                                                                                scanf("%f", &pib2);
                                                                                                                                                    printf("Pontos turísticos: ");
                                                                                                                                                        scanf("%d", &pt2);
                                                                                                                                                            dens2 = pop2 / area2;

                                                                                                                                                                int attr1 = 0, attr2 = 0;
                                                                                                                                                                    float valor1_c1 = 0, valor1_c2 = 0;
                                                                                                                                                                        float valor2_c1 = 0, valor2_c2 = 0;
                                                                                                                                                                            float soma_c1 = 0, soma_c2 = 0;
                                                                                                                                                                                char nome_attr1[30], nome_attr2[30];

                                                                                                                                                                                    // Escolha do primeiro atributo
                                                                                                                                                                                        mostrarMenu(0);
                                                                                                                                                                                            printf("Digite a opção do primeiro atributo: ");
                                                                                                                                                                                                scanf("%d", &attr1);

                                                                                                                                                                                                    // Escolha do segundo atributo (exclui o primeiro)
                                                                                                                                                                                                        mostrarMenu(attr1);
                                                                                                                                                                                                            printf("Digite a opção do segundo atributo: ");
                                                                                                                                                                                                                scanf("%d", &attr2);

                                                                                                                                                                                                                    // Comparações
                                                                                                                                                                                                                        switch(attr1) {
                                                                                                                                                                                                                                case 1: valor1_c1 = pop1; valor1_c2 = pop2; strcpy(nome_attr1, "População"); break;
                                                                                                                                                                                                                                        case 2: valor1_c1 = area1; valor1_c2 = area2; strcpy(nome_attr1, "Área"); break;
                                                                                                                                                                                                                                                case 3: valor1_c1 = pib1; valor1_c2 = pib2; strcpy(nome_attr1, "PIB"); break;
                                                                                                                                                                                                                                                        case 4: valor1_c1 = pt1; valor1_c2 = pt2; strcpy(nome_attr1, "Pontos Turísticos"); break;
                                                                                                                                                                                                                                                                case 5: valor1_c1 = dens1; valor1_c2 = dens2; strcpy(nome_attr1, "Densidade Demográfica"); break;
                                                                                                                                                                                                                                                                        default: printf("Atributo inválido!\n"); return 1;
                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                switch(attr2) {
                                                                                                                                                                                                                                                                                        case 1: valor2_c1 = pop1; valor2_c2 = pop2; strcpy(nome_attr2, "População"); break;
                                                                                                                                                                                                                                                                                                case 2: valor2_c1 = area1; valor2_c2 = area2; strcpy(nome_attr2, "Área"); break;
                                                                                                                                                                                                                                                                                                        case 3: valor2_c1 = pib1; valor2_c2 = pib2; strcpy(nome_attr2, "PIB"); break;
                                                                                                                                                                                                                                                                                                                case 4: valor2_c1 = pt1; valor2_c2 = pt2; strcpy(nome_attr2, "Pontos Turísticos"); break;
                                                                                                                                                                                                                                                                                                                        case 5: valor2_c1 = dens1; valor2_c2 = dens2; strcpy(nome_attr2, "Densidade Demográfica"); break;
                                                                                                                                                                                                                                                                                                                                default: printf("Atributo inválido!\n"); return 1;
                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                        // Regra: maior vence, exceto densidade (menor vence)
                                                                                                                                                                                                                                                                                                                                            float resultado1 = (attr1 == 5) ? (valor1_c1 < valor1_c2 ? 1 : (valor1_c1 > valor1_c2 ? -1 : 0))
                                                                                                                                                                                                                                                                                                                                                                                : (valor1_c1 > valor1_c2 ? 1 : (valor1_c1 < valor1_c2 ? -1 : 0));
                                                                                                                                                                                                                                                                                                                                                                                    float resultado2 = (attr2 == 5) ? (valor2_c1 < valor2_c2 ? 1 : (valor2_c1 > valor2_c2 ? -1 : 0))
                                                                                                                                                                                                                                                                                                                                                                                                                        : (valor2_c1 > valor2_c2 ? 1 : (valor2_c1 < valor2_c2 ? -1 : 0));

                                                                                                                                                                                                                                                                                                                                                                                                                            // Soma para decisão final
                                                                                                                                                                                                                                                                                                                                                                                                                                soma_c1 = valor1_c1 + valor2_c1;
                                                                                                                                                                                                                                                                                                                                                                                                                                    soma_c2 = valor1_c2 + valor2_c2;

                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("\n===== RESULTADO =====\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Carta 1 - %s\n", nome1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("%s: %.2f\n", nome_attr1, valor1_c1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("%s: %.2f\n", nome_attr2, valor2_c1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Soma: %.2f\n\n", soma_c1);

                                                                                                                                                                                                                                                                                                                                                                                                                                                            printf("Carta 2 - %s\n", nome2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("%s: %.2f\n", nome_attr1, valor1_c2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("%s: %.2f\n", nome_attr2, valor2_c2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Soma: %.2f\n\n", soma_c2);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Resultado final
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (soma_c1 > soma_c2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        printf("Resultado: %s venceu!\n", nome1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (soma_c2 > soma_c1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    printf("Resultado: %s venceu!\n", nome2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                printf("Empate!\n");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }